### GET request para obter a lista de analytics disponíveis
GET http://localhost:9090/api/analytics/list

### Exemplo de resposta esperada:
# {
#   "qualAnalytics": [
#     { "name": "Student activity profile", "type": "URL" }
#   ],
#   "quantAnalytics": [
#     { "name": "Evolução pela atividade (%)", "type": "integer" }
#   ]
# }
