### GET request para obter a lista de analytics disponíveis
GET https://0c23-2001-818-df8b-c900-1129-60a-9ec6-c2fb.ngrok-free.app/api/analytics/list

### Exemplo de resposta esperada:
# {
#   "qualAnalytics": [
#     { "name": "Student activity profile", "type": "URL" }
#   ],
#   "quantAnalytics": [
#     { "name": "Evolução pela atividade (%)", "type": "integer" }
#   ]
# }
