### GET request para obter a lista de parâmetros da página de configuração
GET https://0c23-2001-818-df8b-c900-1129-60a-9ec6-c2fb.ngrok-free.app/api/params

### Exemplo de resposta esperada:
# [
#   { "name": "difficulty", "type": "text/plain" },
#   { "name": "time_limit", "type": "integer" },
#   { "name": "scenario", "type": "text/plain" }
# ]
